In [19]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from numpy.random import default_rng

In [22]:
df = pandas.read_csv('data_and_notebook_A3/bm.csv')
df = df.dropna()
df

       6.7593   2.9984  0
0    -2.62890  3.97460  0
1     0.88878 -1.43350  1
2    -2.03500 -3.74210  0
3    -7.43160  0.86322  0
4     1.04550 -2.99510  0
...       ...      ... ..
9994  5.01880 -0.28495  1
9995  7.23240 -0.24904  0
9996 -2.03320 -0.44094  1
9997 -4.49600 -1.99200  1
9998  2.50910  1.92650  0

[9999 rows x 3 columns]

In [23]:
df.columns = ['A', 'B', 'C']
#df.loc[len(df)] = [6.7593, 2.9984, 0]
#df
new_record = pd.DataFrame([[6.7593, 2.9984, 0]], columns=df.columns)
df = pd.concat([new_record, df], ignore_index=True)
df

            A        B  C
0     6.75930  2.99840  0
1    -2.62890  3.97460  0
2     0.88878 -1.43350  1
3    -2.03500 -3.74210  0
4    -7.43160  0.86322  0
...       ...      ... ..
9995  5.01880 -0.28495  1
9996  7.23240 -0.24904  0
9997 -2.03320 -0.44094  1
9998 -4.49600 -1.99200  1
9999  2.50910  1.92650  0

[10000 rows x 3 columns]

In [24]:
X = df[['A', 'B']]
y = df['C']
X

            A        B
0     6.75930  2.99840
1    -2.62890  3.97460
2     0.88878 -1.43350
3    -2.03500 -3.74210
4    -7.43160  0.86322
...       ...      ...
9995  5.01880 -0.28495
9996  7.23240 -0.24904
9997 -2.03320 -0.44094
9998 -4.49600 -1.99200
9999  2.50910  1.92650

[10000 rows x 2 columns]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
type(y_train)
y_test.size

1000

In [26]:
# 5000 sample
rng = np.random.default_rng()
n = 5000

r = np.zeros([n,100], dtype = int)
XX = np.zeros([n, 2, 100])
r[:,0] = rng.choice(n, size = n, replace = True)
XX[:,:,0] = X[r[:,0], :]

InvalidIndexError: (array([4069, 4399, 2073, ...,  319, 4589, 2445]), slice(None, None, None))

In [24]:
# Jonas
rng = np.random.default_rng()
n = 5000
r = np.zeros ([n,100], dtype = int)
XX = np.zeros([n, 2, 100])
for i in range (100):
    r[:,i] = rng.choice(n, size = n, replace = True)
    XX[:,:,i] = X[ r[:,i],:]

InvalidIndexError: (array([3370, 4152, 4375, ..., 1015,  398, 3056]), slice(None, None, None))